export const configuration = {
  assistantName: 'Peptide Research Assistant',
  welcomeMessage: 'I answer from a controlled research library and cite the evidence.',
  responseStyle: 'research-grounded',
  citationRequirement: 'required for substantive answers',
  evidenceThreshold: 'moderate',
  safetyRules: ['No individualized medical dosing', 'No diagnosis or treatment promises', 'Cite evidence when available'],
  domainScope: 'research peptides and published evidence only',
  fallbackMessage: 'I could not find sufficient evidence in the available research library to answer that reliably.',
  maxResponseLength: 700,
  sourceVisibility: 'public-citation-ready',
};

export const researchSources = [
  {
    id: 'bpc-157-2023-meta',
    title: 'Demonstration record: BPC-157 in gastric mucosal repair models',
    authors: ['Sample authors, lab group'],
    year: 2023,
    journal: 'Demonstration Research Review',
    doi: '10.0000/demo.bpc157.2023',
    pubmed: 'PMID 37212345',
    url: 'https://example.org/research/bpc157-gastric-repair',
    sourceType: 'Peer-reviewed article',
    evidenceLevel: 'Tier 3',
    studyType: 'Preclinical',
    peptide: 'BPC-157',
    status: 'active',
    abstract: 'This demonstration preclinical study explored tissue repair and mucosal responses in a controlled animal model. Results suggested a signal of interest in repair-related pathways, but the sample size and model design limit direct extrapolation to human treatment decisions.',
    limitations: 'Animal only; no human data; small sample; mechanistic evidence only.',
    dateAdded: '2026-01-14',
    lastVerified: '2026-08-01',
    notes: 'Demonstration sample only. Not a clinical recommendation.'
  },
  {
    id: 'bpc-157-2021-mechanism',
    title: 'Mechanistic overview of BPC-157 and tissue healing signaling',
    authors: ['Research group'],
    year: 2021,
    journal: 'Peptide Mechanisms Review',
    doi: '10.0000/demo.bpc157.mechanism.2021',
    pubmed: 'PMID 34421010',
    url: 'https://example.org/research/bpc157-mechanism',
    sourceType: 'Review article',
    evidenceLevel: 'Tier 5',
    studyType: 'Mechanistic',
    peptide: 'BPC-157',
    status: 'active',
    abstract: 'A review summarizing hypothetical and experimentally reported tissue repair mechanisms, including angiogenesis and inflammatory signaling. Commentary remains secondary to direct clinical evidence.',
    limitations: 'Narrative synthesis; not primary human evidence; possibly mixed interpretation.',
    dateAdded: '2026-02-08',
    lastVerified: '2026-08-01',
    notes: 'Demonstration sample only.'
  },
  {
    id: 'glp-1-2024-human',
    title: 'Human clinical evidence for GLP-1 receptor pathway modulation in metabolic outcomes',
    authors: ['Clinical evidence consortium'],
    year: 2024,
    journal: 'Journal of Human Metabolic Research',
    doi: '10.0000/demo.glp1.human.2024',
    pubmed: 'PMID 39740583',
    url: 'https://example.org/research/glp1-human-evidence',
    sourceType: 'Clinical trial registry summary',
    evidenceLevel: 'Tier 2',
    studyType: 'Clinical trial',
    peptide: 'GLP-1',
    status: 'active',
    abstract: 'This registered clinical study summarizes metabolic outcomes in a controlled human sample. Findings suggest a pathway effect, but trial design and population scope are limited to specific metabolic contexts.',
    limitations: 'Population-specific; not generalizable to all users; not a prescription guidance source.',
    dateAdded: '2026-03-10',
    lastVerified: '2026-08-03',
    notes: 'Demonstration sample only.'
  },
  {
    id: 'thymosin-alpha-1-2022-human',
    title: 'Clinical observations for thymosin alpha-1 in immune modulation studies',
    authors: ['Translational immunology group'],
    year: 2022,
    journal: 'Translational Immunology Reports',
    doi: '10.0000/demo.ta1.clinical.2022',
    pubmed: 'PMID 36978143',
    url: 'https://example.org/research/thymosin-alpha-1-clinical',
    sourceType: 'Clinical report',
    evidenceLevel: 'Tier 1',
    studyType: 'Human study',
    peptide: 'Thymosin Alpha-1',
    status: 'active',
    abstract: 'This human study reported immune-phenotype changes in a controlled clinical setting. The evidence was promising but remains limited by sample size and protocol heterogeneity.',
    limitations: 'Human evidence exists, but it is not definitive for broader clinical use.',
    dateAdded: '2026-04-12',
    lastVerified: '2026-08-02',
    notes: 'Demonstration sample only.'
  },
  {
    id: 'ghk-cu-2025-review',
    title: 'Narrative evidence summary for GHK-Cu and skin-associated research',
    authors: ['Cosmetic science review board'],
    year: 2025,
    journal: 'Dermal Research Summaries',
    doi: '10.0000/demo.ghkcu.review.2025',
    pubmed: 'PMID 40114309',
    url: 'https://example.org/research/ghk-cu-review',
    sourceType: 'Narrative review',
    evidenceLevel: 'Tier 5',
    studyType: 'Secondary commentary',
    peptide: 'GHK-Cu',
    status: 'pending review',
    abstract: 'A review of skin-related and wound-associated studies notes wide variability in study design and limited direct clinical evidence. The source is useful for contextual background rather than a clinical conclusion.',
    limitations: 'Review quality varies, and evidence is not consistent across studies.',
    dateAdded: '2026-06-30',
    lastVerified: '2026-08-01',
    notes: 'Demonstration sample only.'
  },
  {
    id: 'senior-pt-2024-anecdote',
    title: 'Community report: anecdotal peptide use experiences and outcomes',
    authors: ['Community forum contributors'],
    year: 2024,
    journal: 'Community discussion archive',
    doi: '',
    pubmed: '',
    url: 'https://example.org/research/community-report',
    sourceType: 'Community report',
    evidenceLevel: 'Tier 6',
    studyType: 'Anecdotal',
    peptide: 'General peptide use',
    status: 'archived',
    abstract: 'User-reported experiences in a public forum describe a range of outcomes, but these reports cannot be treated as scientific evidence and often lack baseline controls or verification.',
    limitations: 'No peer review; high risk of reporting bias; not suitable as scientific evidence.',
    dateAdded: '2026-05-19',
    lastVerified: '2026-08-01',
    notes: 'Demonstration sample only; excluded from substantive guidance.'
  }
];

export const adminStats = {
  totalSources: researchSources.length,
  humanStudies: researchSources.filter((item) => item.evidenceLevel === 'Tier 1' || item.studyType === 'Human study').length,
  clinicalTrials: researchSources.filter((item) => item.studyType === 'Clinical trial' || item.evidenceLevel === 'Tier 2').length,
  preclinicalStudies: researchSources.filter((item) => item.studyType === 'Preclinical' || item.evidenceLevel === 'Tier 3').length,
  topics: [...new Set(researchSources.map((item) => item.peptide))].length,
  recentSources: researchSources.slice(0, 3),
  questionsAnswered: 1284,
  abstentions: 76,
  averageResponseTime: '2.1s',
};
